[package]
name = "gauntlet-scenario-runner"
edition.workspace = true

[dependencies]
# workspaces
gauntlet-client.workspace = true

# shared
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[features]
scenario_runner = ["gauntlet-client/scenario_runner"]
