[package]
name = "gauntlet-utils"
edition.workspace = true

[dependencies]
tokio.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tonic.workspace = true
prost.workspace = true
x11rb-protocol.workspace = true
x11rb-async.workspace = true
