name: format
on: [push, pull_request]
jobs:
  rust:
    runs-on: ubuntu-22.04
    steps:
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: actions/checkout@v4
      - name: rustfmt
        run: cargo +nightly fmt --all -- --check
  nix:
    runs-on: ubuntu-22.04
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v4
      - name: alejandra
        run: nix shell nixpkgs#alejandra -c alejandra -c .
