name: format
on: [push, pull_request]
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: actions/checkout@v4
      - name: Check format
        run: cargo +nightly fmt --all -- --check --verbose
